# Generated by Django 2.0.1 on 2018-01-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('effect', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('lifepoints', models.IntegerField(default=8000)),
                ('deck', models.ManyToManyField(related_name='deck', to='Deck.Cards')),
                ('hand', models.ManyToManyField(related_name='hand', to='Deck.Cards')),
            ],
        ),
    ]
